🔄 ci(`tests.yml`): switch to `ubuntu-latest` runner
Getting this error in GitHub Actions:

```
thread 'tokio-rt-worker' (359) panicked at crates/oxc_allocator/src/pool/fixed_size.rs:112:67:
called `Result::unwrap()` on an `Err` value: ()
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
============================================================
Bun v1.4.2 (744846f84) Linux x64
WSL Kernel v6.1.158 | glibc v2.39
CPU: sse42 popcnt avx avx2
Args: "node" "/home/runner/work/gitpaper/gitpaper/node_modules/.bin/oxlint"
Features: Bun.stderr(2) Bun.stdin(2) Bun.stdout(2) bunfig jsc loaders tsconfig tsconfig_paths process_dlopen
Builtins: "bun:main" "node:assert" "node:crypto" "node:fs" "node:fs/promises" "node:module" "node:os" "node:path" "node:tty" "node:url" "node:util" "node:worker_threads"

Elapsed: 781ms | User: 600ms | Sys: 93ms
RSS: 121.83 MB | Peak: 121.83 MB | Commit: 0.23 GB | Faults: 0 | Machine: 5.18 GB

panic: abort() called
oh no: Bun has crashed. This indicates a bug in Bun, not your code.

To send a redacted crash report to Bun's team,
please file a GitHub issue using the link below:

 https://bun.report/1.4.2/ln1744846fgmEukggS2g2nB6npR8vkKyi68Cw948Cysw8Cy670E6nw8Cohn8Xigs2Xw12zX4ix2X2zh9Cixg9CAa

error: script "lint:oxc" was terminated by signal SIGABRT (Abort)
/usr/bin/bash: line 1:   355 Aborted                 bun run lint:oxc
error: script "lint" exited with code 134
Error: Process completed with exit code 134.
```